### ISSUE TITLE
Can we have FTX MM too ?

### ISSUE THREAD

**Issue by babyrig** [sandybradley/pyMarketMaker#2]
Could you make one to FTX too ?

thanks

**Comment by sandybradley** [comment]
Hi, Yes I can. If you send some BTC to the following address, I can test it and send you the script.

BTC: 34iN93SvfDkzaaenXnUv9uHkyYNPPPu9sC

**Comment by babyrig** [comment]
> Hi, Yes I can. If you send some BTC to the following address, I can test it and send you the script.
> 
> BTC: 34iN93SvfDkzaaenXnUv9uHkyYNPPPu9sC

This address is from FTX already ? (I think due higher fees on the network will be better to deposit directly there to you test). Don't forget to use some code to have $5 discount fees.

**Comment by sandybradley** [comment]
Yes, this is my FTX BTC address. Then I can test if the code works on live
accounts.

**Comment by babyrig** [comment]
Do you used the code to have the $5 on discount fees ? If not just look to someone who are FTX ambassador with their code to have this discount I think will be good to tests. I hope you can have this working on leveraged tokens too. Already contacted some friends to help with btc too.

**Comment by sandybradley** [comment]
https://github.com/sandybradley/FTX_Market_Maker
